server:
  port: 443

lavalink:
  server:
    password: "mypassword"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      http: true
      local: false

logging:
  level:
    root: INFO
